// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class MessageDto {
  MessageDto({
    required this.id,
    required this.name,
    required this.message,
    required this.createdAt,
  });

  String id;

  String name;

  String message;

  String createdAt;

  Object encode() {
    return <Object?>[
      id,
      name,
      message,
      createdAt,
    ];
  }

  static MessageDto decode(Object result) {
    result as List<Object?>;
    return MessageDto(
      id: result[0]! as String,
      name: result[1]! as String,
      message: result[2]! as String,
      createdAt: result[3]! as String,
    );
  }
}

class _MessagingApiCodec extends StandardMessageCodec {
  const _MessagingApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is MessageDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is MessageDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return MessageDto.decode(readValue(buffer)!);
      case 129: 
        return MessageDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// MessagingApi
class MessagingApi {
  /// Constructor for [MessagingApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MessagingApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : __pigeon_binaryMessenger = binaryMessenger,
        __pigeon_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _MessagingApiCodec();

  final String __pigeon_messageChannelSuffix;

  Future<List<MessageDto?>> getMessages() async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.messages.MessagingApi.getMessages$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<MessageDto?>();
    }
  }

  Future<MessageDto> sendMessage(MessageDto message) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.messages.MessagingApi.sendMessage$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[message]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as MessageDto?)!;
    }
  }
}

class _FlutterMessagingApiCodec extends StandardMessageCodec {
  const _FlutterMessagingApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is MessageDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is MessageDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return MessageDto.decode(readValue(buffer)!);
      case 129: 
        return MessageDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FlutterMessagingApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _FlutterMessagingApiCodec();

  Future<List<MessageDto?>> getMessages();

  Future<MessageDto> sendMessage(MessageDto message);

  static void setUp(FlutterMessagingApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.messages.FlutterMessagingApi.getMessages$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          try {
            final List<MessageDto?> output = await api.getMessages();
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.messages.FlutterMessagingApi.sendMessage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.messages.FlutterMessagingApi.sendMessage was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MessageDto? arg_message = (args[0] as MessageDto?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.messages.FlutterMessagingApi.sendMessage was null, expected non-null MessageDto.');
          try {
            final MessageDto output = await api.sendMessage(arg_message!);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
