// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct MessageDto {
  var id: String
  var name: String
  var message: String
  var createdAt: String

  static func fromList(_ list: [Any?]) -> MessageDto? {
    let id = list[0] as! String
    let name = list[1] as! String
    let message = list[2] as! String
    let createdAt = list[3] as! String

    return MessageDto(
      id: id,
      name: name,
      message: message,
      createdAt: createdAt
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      message,
      createdAt,
    ]
  }
}
private class MessagingApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return MessageDto.fromList(self.readValue() as! [Any?])
    case 129:
      return MessageDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagingApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MessageDto {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? MessageDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagingApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagingApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagingApiCodecWriter(data: data)
  }
}

class MessagingApiCodec: FlutterStandardMessageCodec {
  static let shared = MessagingApiCodec(readerWriter: MessagingApiCodecReaderWriter())
}

/// MessagingApi
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MessagingApi {
  func getMessages() throws -> [MessageDto]
  func sendMessage(message: MessageDto) throws -> MessageDto
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MessagingApiSetup {
  /// The codec used by MessagingApi.
  static var codec: FlutterStandardMessageCodec { MessagingApiCodec.shared }
  /// Sets up an instance of `MessagingApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MessagingApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getMessagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.messages.MessagingApi.getMessages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMessagesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMessages()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMessagesChannel.setMessageHandler(nil)
    }
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.messages.MessagingApi.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! MessageDto
        do {
          let result = try api.sendMessage(message: messageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
  }
}
private class FlutterMessagingApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return MessageDto.fromList(self.readValue() as! [Any?])
    case 129:
      return MessageDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FlutterMessagingApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MessageDto {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? MessageDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterMessagingApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterMessagingApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterMessagingApiCodecWriter(data: data)
  }
}

class FlutterMessagingApiCodec: FlutterStandardMessageCodec {
  static let shared = FlutterMessagingApiCodec(readerWriter: FlutterMessagingApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FlutterMessagingApiProtocol {
  func getMessages(completion: @escaping (Result<[MessageDto], FlutterError>) -> Void)
  func sendMessage(message messageArg: MessageDto, completion: @escaping (Result<MessageDto, FlutterError>) -> Void)
}
class FlutterMessagingApi: FlutterMessagingApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: FlutterStandardMessageCodec {
    return FlutterMessagingApiCodec.shared
  }
  func getMessages(completion: @escaping (Result<[MessageDto], FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.messages.FlutterMessagingApi.getMessages\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(FlutterError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! [MessageDto]
        completion(.success(result))
      }
    }
  }
  func sendMessage(message messageArg: MessageDto, completion: @escaping (Result<MessageDto, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.messages.FlutterMessagingApi.sendMessage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(FlutterError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! MessageDto
        completion(.success(result))
      }
    }
  }
}
