// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class MessageDto;

@interface MessageDto : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    name:(NSString *)name
    message:(NSString *)message
    createdAt:(NSString *)createdAt;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, copy) NSString * message;
@property(nonatomic, copy) NSString * createdAt;
@end

/// The codec used by MessagingApi.
NSObject<FlutterMessageCodec> *MessagingApiGetCodec(void);

/// MessagingApi
@protocol MessagingApi
/// @return `nil` only when `error != nil`.
- (nullable NSArray<MessageDto *> *)getMessagesWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable MessageDto *)sendMessageMessage:(MessageDto *)message error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpMessagingApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MessagingApi> *_Nullable api);

extern void SetUpMessagingApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MessagingApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
